<?php

/**
 * Need to create an Axis table for items like database_schema_version (for site updates)
 */

$schema['0.01']['create']['database'] = [
    'name' => $dbInsertDatabase,
    'charset' => 'utf8',
    'collation' => 'utf8_general_ci',
];

$schema['0.01']['create']['table']['languages'] = [
    [
        'name' => 'id',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '1',
        'default' => '',
        'primary_key' => '1',
        'unique_key' => '',
    ],
    [
        'name' => 'name',
        'type' => 'varchar(20)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '1',
    ],
    [
        'name' => 'folder_name',
        'type' => 'varchar(20)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'created',
        'type' => 'timestamp',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => "'0000-00-00 00:00:00'",
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'modified',
        'type' => 'timestamp',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => 'CURRENT_TIMESTAMP',
        'primary_key' => '',
        'unique_key' => '',
    ],
];

$schema['0.01']['create']['table']['links'] = [
    [
        'name' => 'id',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '1',
        'default' => '',
        'primary_key' => '1',
        'unique_key' => '',
    ],
    [
        'name' => 'label',
        'type' => 'varchar(50)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'url',
        'type' => 'varchar(100)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'comment',
        'type' => 'text',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'parent',
        'type' => 'varchar(20)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'location',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '1',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'user_classes',
        'type' => 'varchar(100)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'link_order',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '1',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'active',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '1',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'created',
        'type' => 'timestamp',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => "'0000-00-00 00:00:00'",
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'modified',
        'type' => 'timestamp',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => 'CURRENT_TIMESTAMP',
        'primary_key' => '',
        'unique_key' => '',
    ],
];

$schema['0.01']['create']['table']['plugins'] = [
    [
        'name' => 'id',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '1',
        'default' => '',
        'primary_key' => '1',
        'unique_key' => '',
    ],
    [
        'name' => 'name',
        'type' => 'varchar(50)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '1',
    ],
    [
        'name' => 'version',
        'type' => 'varchar(20)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'folder_path',
        'type' => 'varchar(255)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'folder_name',
        'type' => 'varchar(100)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'description',
        'type' => 'text',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'developer',
        'type' => 'varchar(50)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'developer_email',
        'type' => 'varchar(100)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '0',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'developer_site',
        'type' => 'varchar(100)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'user_classes',
        'type' => 'varchar(100)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'active',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '2',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'created',
        'type' => 'timestamp',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => "'0000-00-00 00:00:00'",
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'modified',
        'type' => 'timestamp',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => 'CURRENT_TIMESTAMP',
        'primary_key' => '',
        'unique_key' => '',
    ],
];

$schema['0.01']['create']['table']['schemas'] = [
    [
        'name' => 'system_name',
        'type' => 'varchar(20)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'schema_version',
        'type' => 'varchar(20)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '1',
    ],
    [
        'name' => 'created',
        'type' => 'timestamp',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => "'0000-00-00 00:00:00'",
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'modified',
        'type' => 'timestamp',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => 'CURRENT_TIMESTAMP',
        'primary_key' => '',
        'unique_key' => '',
    ],
];

$schema['0.01']['create']['table']['themes'] = [
    [
        'name' => 'id',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '1',
        'default' => '',
        'primary_key' => '1',
        'unique_key' => '',
    ],
    [
        'name' => 'name',
        'type' => 'varchar(50)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '1',
    ],
    [
        'name' => 'version',
        'type' => 'varchar(20)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'folder_path',
        'type' => 'varchar(255)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'folder_name',
        'type' => 'varchar(100)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'description',
        'type' => 'text',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'artist',
        'type' => 'varchar(50)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'artist_email',
        'type' => 'varchar(100)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'artist_site',
        'type' => 'varchar(100)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'selectable',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '2',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'active',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '1',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'created',
        'type' => 'timestamp',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => "'0000-00-00 00:00:00'",
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'modified',
        'type' => 'timestamp',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => 'CURRENT_TIMESTAMP',
        'primary_key' => '',
        'unique_key' => '',
    ],
];

$schema['0.01']['create']['table']['users'] = [
    [
        'name' => 'id',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '1',
        'default' => '',
        'primary_key' => '1',
        'unique_key' => '',
    ],
    [
        'name' => 'login_name',
        'type' => 'varchar(20)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '1',
    ],
    [
        'name' => 'display_name',
        'type' => 'varchar(20)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'real_name',
        'type' => 'varchar(50)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'password',
        'type' => 'varchar(125)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'email_address',
        'type' => 'varchar(100)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '1',
    ],
    [
        'name' => 'hide_email_address',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '2',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'timezone_offset',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => "'0'",
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'location',
        'type' => 'varchar(200)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'website',
        'type' => 'varchar(100)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'avatar',
        'type' => 'varchar(255)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'bio',
        'type' => 'text',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'signature',
        'type' => 'text',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'preferred_theme',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '1',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'user_classes',
        'type' => 'varchar(100)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'last_ip',
        'type' => 'varchar(20)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'last_login_time',
        'type' => 'timestamp',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => "'0000-00-00 00:00:00'",
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'registration_ip',
        'type' => 'varchar(20)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'created',
        'type' => 'timestamp',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => "'0000-00-00 00:00:00'",
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'modified',
        'type' => 'timestamp',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => 'CURRENT_TIMESTAMP',
        'primary_key' => '',
        'unique_key' => '',
    ],
];

$schema['0.01']['create']['table']['venues'] = [
    [
        'name' => 'id',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '1',
        'default' => '',
        'primary_key' => '1',
        'unique_key' => '',
    ],
    [
        'name' => 'name',
        'type' => 'varchar(20)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '1',
    ],
    [
        'name' => 'title',
        'type' => 'varchar(50)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'tagline',
        'type' => 'varchar(200)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'description',
        'type' => 'text',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'keywords',
        'type' => 'text',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'venue_email',
        'type' => 'varchar(100)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '1',
    ],
    [
        'name' => 'venue_email_name',
        'type' => 'varchar(100)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'venue_admin',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '1',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'active_theme',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '1',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'default_plugin',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '1',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'maintenance_flag',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '1',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'maintenance_flag_text',
        'type' => 'text',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'language',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '1',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'active',
        'type' => 'int(11)',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => '2',
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'created',
        'type' => 'timestamp',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => "'0000-00-00 00:00:00'",
        'primary_key' => '',
        'unique_key' => '',
    ],
    [
        'name' => 'modified',
        'type' => 'timestamp',
        'not_null' => '1',
        'signed' => '0',
        'autoincrement' => '0',
        'default' => 'CURRENT_TIMESTAMP',
        'primary_key' => '',
        'unique_key' => '',
    ],
];


$schema['0.01']['insert']['table'] = [
    [
        'languages' => [
            [
                'id' => '',
                'name' => 'English',
                'folder_name' => 'english',
                'created' => '',
                'modified' => ''
            ],
        ],
        'links' => [
            [
                'id' => '',
                'label' => 'Home',
                'url' => '',
                'comment' => '',
                'parent' => '',
                'location' => 1,
                'user_classes' => '',
                'link_order' => 1,
                'active' => 2,
                'created' => $currentMySqlTimestamp,
                'modified' => $currentMySqlTimestamp,
            ],
            [
                'id' => '',
                'label' => 'Ciao Folks',
                'url' => '/hello/hey',
                'comment' => '',
                'parent' => '',
                'location' => 1,
                'user_classes' => '',
                'link_order' => 2,
                'active' => 2,
                'created' => $currentMySqlTimestamp,
                'modified' => $currentMySqlTimestamp,
            ],
            [
                'id' => '',
                'label' => 'Ciao People',
                'url' => '/hello/later',
                'comment' => '',
                'parent' => '',
                'location' => 1,
                'user_classes' => '',
                'link_order' => 3,
                'active' => 2,
                'created' => $currentMySqlTimestamp,
                'modified' => $currentMySqlTimestamp,
            ],
            [
                'id' => '',
                'label' => 'Ciao Admin',
                'url' => '/admin/hello',
                'comment' => '',
                'parent' => '',
                'location' => 1,
                'user_classes' => '',
                'link_order' => 4,
                'active' => 2,
                'created' => $currentMySqlTimestamp,
                'modified' => $currentMySqlTimestamp,
            ],
            [
                'id' => '',
                'label' => 'AllianceCMS Wiki',
                'url' => 'https://github.com/jbWebWare/AllianceCMS/wiki',
                'comment' => '',
                'parent' => '',
                'location' => 1,
                'user_classes' => '',
                'link_order' => 5,
                'active' => 2,
                'created' => $currentMySqlTimestamp,
                'modified' => $currentMySqlTimestamp,
            ],
        ],
        'plugins' => [
            [
                'id' => '',
                'name' => 'Home',
                'version' => '0.01',
                'folder_path' => 'axis/plugins/',
                'folder_name' => 'Home',
                'description' => 'This AllianceCMS plugin allows you to manage your home page.',
                'developer' => 'Jesse Burns',
                'developer_email' => 'jesse.burns@alliancecms.com',
                'developer_site' => 'http://www.alliancecms.com',
                'user_classes' => '',
                'active' => 2,
                'created' => $currentMySqlTimestamp,
                'modified' => $currentMySqlTimestamp,
            ],
            [
                'id' => '',
                'name' => 'PluginManager',
                'version' => '0.01',
                'folder_path' => 'axis/plugins/',
                'folder_name' => 'PluginManager',
                'description' => 'Plugin Manager for AllianceCMS.',
                'developer' => 'Jesse Burns',
                'developer_email' => 'jesse.burns@alliancecms.com',
                'developer_site' => 'http://www.alliancecms.com',
                'user_classes' => '',
                'active' => 2,
                'created' => $currentMySqlTimestamp,
                'modified' => $currentMySqlTimestamp,
            ],
            [
                'id' => '',
                'name' => 'Example',
                'version' => '0.01',
                'folder_path' => 'axis/plugins/',
                'folder_name' => 'Example',
                'description' => 'This AllianceCMS plugin will show you how to properly create a quality plugin.',
                'developer' => 'Jesse Burns',
                'developer_email' => 'jesse.burns@alliancecms.com',
                'developer_site' => 'http://www.alliancecms.com',
                'user_classes' => '',
                'active' => 2,
                'created' => $currentMySqlTimestamp,
                'modified' => $currentMySqlTimestamp,
            ],
            [
                'id' => '',
                'name' => 'Ciao',
                'version' => '0.01',
                'folder_path' => 'axis/plugins/',
                'folder_name' => 'Ciao',
                'description' => 'This is a simple take on the classic "Hello World!" plugin, AllianceCMS style.',
                'developer' => 'Jesse Burns',
                'developer_email' => 'jesse.burns@alliancecms.com',
                'developer_site' => 'http://www.alliancecms.com',
                'user_classes' => '',
                'active' => 2,
                'created' => $currentMySqlTimestamp,
                'modified' => $currentMySqlTimestamp,
            ],
        ],
        'themes' => [
            [
                'id' => '',
                'name' => 'Emplode',
                'version' => '0.01',
                'folder_path' => 'themes/',
                'folder_name' => 'Emplode',
                'description' => 'This theme is an AllianceCMS port of the Emplode website template found @ http://templates.arcsin.se.',
                'artist' => 'Jesse Burns',
                'artist_email' => 'jesse.burns@alliancecms.com',
                'artist_site' => 'http://www.alliancecms.com',
                'selectable' => '',
                'active' => 2,
                'created' => $currentMySqlTimestamp,
                'modified' => $currentMySqlTimestamp,
            ],
        ],
        'users' => [
            [
                'id' => '',
                'login_name' => $adminInsertLoginName,
                'display_name' => $adminInsertDisplayName,
                'real_name' => $adminInsertRealName,
                'password' => $adminInsertPassword,
                'email_address' => $adminInsertEmail,
                'hide_email_address' => $adminInsertHideEmail,
                'timezone_offset' => '',
                'location' => $adminInsertLocation,
                'website' => $adminInsertWebsite,
                'avatar' => $adminInsertAvatar,
                'bio' => $adminInsertBio,
                'signature' => $adminInsertSignature,
                'preferred_theme' => '',
                'user_classes' => '',
                'last_ip' => "'".getenv('REMOTE_ADDR')."'",
                'last_login_time' => $currentMySqlTimestamp,
                'registration_ip' => "'".getenv('REMOTE_ADDR')."'",
                'created' => $currentMySqlTimestamp,
                'modified' => $currentMySqlTimestamp,
            ],
        ],
        'venues' => [
            [
                'id' => '',
                'name' => $venueInsertName,
                'title' => $venueInsertTitle,
                'tagline' => $venueInsertTagline,
                'description' => $venueInsertDescription,
                'keywords' => $venueInsertKeywords,
                'venue_email' => $venueInsertEmail,
                'venue_email_name' => $venueInsertEmailName,
                'venue_admin' => 1,
                'active_theme' => 1,
                'default_plugin' => 1,
                'maintenance_flag' => 1,
                'maintenance_flag_text' => '',
                'language' => $languageInsert,
                'active' => 2,
                'created' => $currentMySqlTimestamp,
                'modified' => $currentMySqlTimestamp,
            ],
        ],
    ],
];

$schema['0.01']['alter']['table'] = '';
